//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CandOrdRespySol.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CandOrdRespySol.RecursosLocalizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respuestas.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solucion.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESPUESTA.
        /// </summary>
        internal static string lbl1 {
            get {
                return ResourceManager.GetString("lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLUCION.
        /// </summary>
        internal static string lbl2 {
            get {
                return ResourceManager.GetString("lbl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celdas.
        /// </summary>
        internal static string lbl2Celda2 {
            get {
                return ResourceManager.GetString("lbl2Celda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celdas.
        /// </summary>
        internal static string lblCelda1 {
            get {
                return ResourceManager.GetString("lblCelda1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celdas.
        /// </summary>
        internal static string lblCelda2 {
            get {
                return ResourceManager.GetString("lblCelda2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abrir Ejercicio.
        /// </summary>
        internal static string mIAbrir {
            get {
                return ResourceManager.GetString("mIAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comparar Respuesta.
        /// </summary>
        internal static string mIComparar {
            get {
                return ResourceManager.GetString("mIComparar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMAS-LANGUAGES.
        /// </summary>
        internal static string mIdiomas {
            get {
                return ResourceManager.GetString("mIdiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string mIEspañol {
            get {
                return ResourceManager.GetString("mIEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string mIIngles {
            get {
                return ResourceManager.GetString("mIIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portugues.
        /// </summary>
        internal static string mIPortugues {
            get {
                return ResourceManager.GetString("mIPortugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESPUESTA Y SOLUCION.
        /// </summary>
        internal static string mRS {
            get {
                return ResourceManager.GetString("mRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos Ordenados Respuesta y Solución.
        /// </summary>
        internal static string thisText {
            get {
                return ResourceManager.GetString("thisText", resourceCulture);
            }
        }
    }
}
